import { AuthEventPatterns, EventTypes } from '@lms/shared-types';

export const NOTIFICATION_RABBITMQ_CLIENT = 'NOTIFICATION_RABBITMQ_CLIENT';

export const ROUTING_KEYS = {
  AUTH_REGISTERED: AuthEventPatterns.USER_REGISTERED,
  ASSIGNMENT_GRADED: EventTypes.ASSIGNMENT_SUBMISSION_GRADED,
  QUIZ_COMPLETED: EventTypes.QUIZ_ATTEMPT_SUBMITTED,
  COURSE_ENROLLED: EventTypes.ENROLLMENT_CREATED,
  PAYMENT_CONFIRMED: EventTypes.PAYMENT_CONFIRMED,
  PAYMENT_FAILED: EventTypes.PAYMENT_FAILED,
} as const;
