import { EventTypes } from '@lms/shared-types';

export const CERT_RABBITMQ_CLIENT = 'CERT_RABBITMQ_CLIENT';

export const ROUTING_KEYS = {
  ENROLLMENT_COMPLETED: EventTypes.ENROLLMENT_COMPLETED,
  CERTIFICATE_ISSUED: EventTypes.CERTIFICATE_ISSUED,
  CERTIFICATE_REVOKED: EventTypes.CERTIFICATE_REVOKED,
} as const;
